import type { VocabularyItem } from "./types"

export const OXFORD_3000: VocabularyItem[] = [
  {
    english: "a, an",
    vietnamese: "một",
    type: "indefinite article",
    example_en: "I need a pen and an eraser.",
    example_vn: "Tôi cần một cây bút và một cục tẩy.",
  },
  {
    english: "abandon",
    vietnamese: "từ bỏ, bỏ rơi",
    type: "v",
    example_en: "He abandoned the plan because it was too risky.",
    example_vn: "Anh ấy từ bỏ kế hoạch vì nó quá rủi ro.",
  },
  {
    english: "ability",
    vietnamese: "khả năng",
    type: "n",
    example_en: "She has the ability to work under pressure.",
    example_vn: "Cô ấy có khả năng làm việc dưới áp lực.",
  },
  {
    english: "able",
    vietnamese: "có khả năng",
    type: "adj",
    example_en: "He is able to finish the job on time.",
    example_vn: "Anh ấy có thể hoàn thành công việc đúng hạn.",
  },
  {
    english: "about",
    vietnamese: "về, khoảng",
    type: "prep., adv.",
    example_en: "We talked about the project.",
    example_vn: "Chúng tôi nói về dự án.",
  },
  {
    english: "above",
    vietnamese: "ở trên, phía trên",
    type: "prep., adv.",
    example_en: "The picture is above the sofa.",
    example_vn: "Bức tranh ở phía trên ghế sofa.",
  },
  {
    english: "abroad",
    vietnamese: "ở nước ngoài",
    type: "adv",
    example_en: "She studied abroad for two years.",
    example_vn: "Cô ấy du học nước ngoài trong hai năm.",
  },
  {
    english: "absolute",
    vietnamese: "tuyệt đối",
    type: "adj",
    example_en: "We need absolute trust in this team.",
    example_vn: "Chúng ta cần sự tin tưởng tuyệt đối trong đội này.",
  },
  {
    english: "absolutely",
    vietnamese: "hoàn toàn, chắc chắn",
    type: "adv",
    example_en: "I absolutely agree with you.",
    example_vn: "Tôi hoàn toàn đồng ý với bạn.",
  },
  {
    english: "academic",
    vietnamese: "thuộc học thuật",
    type: "adj",
    example_en: "She has an academic background in engineering.",
    example_vn: "Cô ấy có nền tảng học thuật về kỹ thuật.",
  },
  {
    english: "accept",
    vietnamese: "chấp nhận",
    type: "v",
    example_en: "He accepted the job offer.",
    example_vn: "Anh ấy đã chấp nhận lời mời làm việc.",
  },
  {
    english: "acceptable",
    vietnamese: "có thể chấp nhận được",
    type: "adj",
    example_en: "This solution is acceptable to everyone.",
    example_vn: "Giải pháp này có thể chấp nhận được với mọi người.",
  },
  {
    english: "access",
    vietnamese: "quyền truy cập; truy cập",
    type: "n., v.",
    example_en: "You can access the system with this password.",
    example_vn: "Bạn có thể truy cập hệ thống bằng mật khẩu này.",
  },
  {
    english: "accident",
    vietnamese: "tai nạn",
    type: "n",
    example_en: "He was injured in a traffic accident.",
    example_vn: "Anh ấy bị thương trong một vụ tai nạn giao thông.",
  },
  {
    english: "accompany",
    vietnamese: "đi cùng",
    type: "v",
    example_en: "She accompanied her friend to the hospital.",
    example_vn: "Cô ấy đi cùng bạn mình đến bệnh viện.",
  },
  {
    english: "according to",
    vietnamese: "theo như",
    type: "prep",
    example_en: "According to the report, sales are increasing.",
    example_vn: "Theo báo cáo, doanh số đang tăng.",
  },
  {
    english: "account",
    vietnamese: "tài khoản; giải thích",
    type: "n., v.",
    example_en: "I created a new email account.",
    example_vn: "Tôi đã tạo một tài khoản email mới.",
  },
  {
    english: "accurate",
    vietnamese: "chính xác",
    type: "adj",
    example_en: "The information is accurate.",
    example_vn: "Thông tin này chính xác.",
  },
  {
    english: "accuse",
    vietnamese: "buộc tội, cáo buộc",
    type: "v",
    example_en: "He was accused of stealing money.",
    example_vn: "Anh ấy bị cáo buộc ăn cắp tiền.",
  },
  {
    english: "achieve",
    vietnamese: "đạt được",
    type: "v",
    example_en: "She achieved her goal after years of hard work.",
    example_vn: "Cô ấy đã đạt được mục tiêu sau nhiều năm nỗ lực.",
  },
  {
    english: "achievement",
    vietnamese: "thành tựu, thành tích",
    type: "n",
    example_en: "Graduating from university was a major achievement for her.",
    example_vn: "Tốt nghiệp đại học là một thành tựu lớn đối với cô ấy.",
  },
  {
    english: "acknowledge",
    vietnamese: "thừa nhận, công nhận",
    type: "v",
    example_en: "He acknowledged his mistake.",
    example_vn: "Anh ấy thừa nhận sai lầm của mình.",
  },
  {
    english: "acquire",
    vietnamese: "đạt được, thu được",
    type: "v",
    example_en: "She acquired new skills at work.",
    example_vn: "Cô ấy học được những kỹ năng mới trong công việc.",
  },
  {
    english: "across",
    vietnamese: "băng qua, ở phía bên kia",
    type: "prep., adv.",
    example_en: "The bank is across the street.",
    example_vn: "Ngân hàng ở phía bên kia đường.",
  },
  {
    english: "act",
    vietnamese: "hành động; diễn xuất",
    type: "v., n.",
    example_en: "He decided to act quickly.",
    example_vn: "Anh ấy quyết định hành động nhanh chóng.",
  },
  {
    english: "action",
    vietnamese: "hành động",
    type: "n",
    example_en: "We need to take action now.",
    example_vn: "Chúng ta cần hành động ngay bây giờ.",
  },
  {
    english: "active",
    vietnamese: "năng động, tích cực",
    type: "adj",
    example_en: "She is very active in community projects.",
    example_vn: "Cô ấy rất tích cực trong các hoạt động cộng đồng.",
  },
  {
    english: "activity",
    vietnamese: "hoạt động",
    type: "n",
    example_en: "Outdoor activities are good for health.",
    example_vn: "Các hoạt động ngoài trời tốt cho sức khỏe.",
  },
  {
    english: "actor",
    vietnamese: "nam diễn viên",
    type: "n",
    example_en: "He is a famous actor.",
    example_vn: "Anh ấy là một nam diễn viên nổi tiếng.",
  },
  {
    english: "actress",
    vietnamese: "nữ diễn viên",
    type: "n",
    example_en: "The actress won an award for her role.",
    example_vn: "Nữ diễn viên đã giành giải thưởng cho vai diễn của mình.",
  },
  {
    english: "actual",
    vietnamese: "thực tế, thực sự",
    type: "adj",
    example_en: "The actual cost was higher than expected.",
    example_vn: "Chi phí thực tế cao hơn dự kiến.",
  },
  {
    english: "actually",
    vietnamese: "thực ra, thật sự",
    type: "adv",
    example_en: "I actually like this idea.",
    example_vn: "Thực ra tôi thích ý tưởng này.",
  },
  {
    english: "ad",
    vietnamese: "quảng cáo",
    type: "n",
    example_en: "I saw this product in an online ad.",
    example_vn: "Tôi thấy sản phẩm này trong một quảng cáo trực tuyến.",
  },
  {
    english: "adapt",
    vietnamese: "thích nghi, điều chỉnh",
    type: "v",
    example_en: "She adapted quickly to the new environment.",
    example_vn: "Cô ấy nhanh chóng thích nghi với môi trường mới.",
  },
  {
    english: "add",
    vietnamese: "thêm vào",
    type: "v",
    example_en: "Please add some sugar to the coffee.",
    example_vn: "Vui lòng thêm một ít đường vào cà phê.",
  },
  {
    english: "addition",
    vietnamese: "sự bổ sung",
    type: "n",
    example_en: "This room is a recent addition to the house.",
    example_vn: "Căn phòng này là phần được bổ sung gần đây của ngôi nhà.",
  },
  {
    english: "additional",
    vietnamese: "thêm, bổ sung",
    type: "adj",
    example_en: "There will be an additional charge.",
    example_vn: "Sẽ có một khoản phí bổ sung.",
  },
  {
    english: "address",
    vietnamese: "địa chỉ; giải quyết",
    type: "n., v.",
    example_en: "Please write your address here.",
    example_vn: "Vui lòng ghi địa chỉ của bạn vào đây.",
  },
  {
    english: "administration",
    vietnamese: "sự quản lý, ban quản trị",
    type: "n",
    example_en: "The school administration announced new rules.",
    example_vn: "Ban quản trị nhà trường đã công bố các quy định mới.",
  },
  {
    english: "admire",
    vietnamese: "ngưỡng mộ, khâm phục",
    type: "v",
    example_en: "I admire her dedication to her work.",
    example_vn: "Tôi ngưỡng mộ sự tận tâm của cô ấy với công việc.",
  },
  {
    english: "admit",
    vietnamese: "thừa nhận",
    type: "v",
    example_en: "He admitted that he was wrong.",
    example_vn: "Anh ấy thừa nhận rằng mình đã sai.",
  },
  {
    english: "adopt",
    vietnamese: "nhận nuôi; áp dụng",
    type: "v",
    example_en: "They decided to adopt a child.",
    example_vn: "Họ quyết định nhận nuôi một đứa trẻ.",
  },
  {
    english: "adult",
    vietnamese: "người trưởng thành; trưởng thành",
    type: "n., adj.",
    example_en: "Only adults are allowed to enter.",
    example_vn: "Chỉ người trưởng thành mới được phép vào.",
  },
  {
    english: "advance",
    vietnamese: "sự tiến bộ; tiến lên; tiên tiến",
    type: "n., v., adj.",
    example_en: "Technology continues to advance rapidly.",
    example_vn: "Công nghệ tiếp tục tiến bộ nhanh chóng.",
  },
  {
    english: "advanced",
    vietnamese: "tiên tiến, nâng cao",
    type: "adj",
    example_en: "This is an advanced training course.",
    example_vn: "Đây là một khóa đào tạo nâng cao.",
  },
  {
    english: "advantage",
    vietnamese: "lợi thế",
    type: "n",
    example_en: "This job offers many advantages.",
    example_vn: "Công việc này mang lại nhiều lợi thế.",
  },
  {
    english: "adventure",
    vietnamese: "cuộc phiêu lưu",
    type: "n",
    example_en: "They went on an exciting adventure.",
    example_vn: "Họ đã tham gia một chuyến phiêu lưu thú vị.",
  },
  {
    english: "advertise",
    vietnamese: "quảng cáo",
    type: "v",
    example_en: "The company advertises its products online.",
    example_vn: "Công ty quảng cáo sản phẩm của mình trên mạng.",
  },
  {
    english: "advertisement",
    vietnamese: "quảng cáo",
    type: "n",
    example_en: "I saw an advertisement for that phone.",
    example_vn: "Tôi thấy một quảng cáo về chiếc điện thoại đó.",
  },
  {
    english: "advertising",
    vietnamese: "hoạt động quảng cáo",
    type: "n",
    example_en: "Advertising plays an important role in business.",
    example_vn: "Quảng cáo đóng vai trò quan trọng trong kinh doanh.",
  },
  {
    english: "advice",
    vietnamese: "lời khuyên",
    type: "n",
    example_en: "She gave me some useful advice.",
    example_vn: "Cô ấy cho tôi một vài lời khuyên hữu ích.",
  },
  {
    english: "advise",
    vietnamese: "khuyên",
    type: "v",
    example_en: "I advise you to rest more.",
    example_vn: "Tôi khuyên bạn nên nghỉ ngơi nhiều hơn.",
  },
  {
    english: "affair",
    vietnamese: "vấn đề, sự việc",
    type: "n",
    example_en: "This is a private affair.",
    example_vn: "Đây là một vấn đề riêng tư.",
  },
  {
    english: "affect",
    vietnamese: "ảnh hưởng",
    type: "v",
    example_en: "Stress can affect your health.",
    example_vn: "Căng thẳng có thể ảnh hưởng đến sức khỏe của bạn.",
  },
  {
    english: "afford",
    vietnamese: "có đủ khả năng chi trả",
    type: "v",
    example_en: "I cannot afford a new car.",
    example_vn: "Tôi không đủ khả năng mua xe mới.",
  },
  {
    english: "afraid",
    vietnamese: "sợ",
    type: "adj",
    example_en: "She is afraid of dogs.",
    example_vn: "Cô ấy sợ chó.",
  },
  {
    english: "after",
    vietnamese: "sau",
    type: "prep., conj., adv.",
    example_en: "We went home after work.",
    example_vn: "Chúng tôi về nhà sau giờ làm.",
  },
  {
    english: "afternoon",
    vietnamese: "buổi chiều",
    type: "n",
    example_en: "I will see you this afternoon.",
    example_vn: "Tôi sẽ gặp bạn vào chiều nay.",
  },
  {
    english: "afterward",
    vietnamese: "sau đó",
    type: "adv",
    example_en: "We had dinner and afterward watched a movie.",
    example_vn: "Chúng tôi ăn tối và sau đó xem phim.",
  },
  {
    english: "again",
    vietnamese: "lại, lần nữa",
    type: "adv",
    example_en: "Please say that again.",
    example_vn: "Vui lòng nói lại lần nữa.",
  },
  {
    english: "against",
    vietnamese: "chống lại, đối với",
    type: "prep.",
    example_en: "I am against this decision.",
    example_vn: "Tôi phản đối quyết định này.",
  },
  {
    english: "age",
    vietnamese: "tuổi; già đi",
    type: "n., v.",
    example_en: "What is your age?",
    example_vn: "Bạn bao nhiêu tuổi?",
  },
  {
    english: "agency",
    vietnamese: "cơ quan, đại lý",
    type: "n",
    example_en: "She works for a travel agency.",
    example_vn: "Cô ấy làm việc cho một công ty du lịch.",
  },
  {
    english: "agenda",
    vietnamese: "chương trình nghị sự, kế hoạch",
    type: "n",
    example_en: "Let us start with the first item on the agenda.",
    example_vn: "Hãy bắt đầu với mục đầu tiên trong chương trình.",
  },
  {
    english: "agent",
    vietnamese: "đại lý, người đại diện",
    type: "n",
    example_en: "He contacted his insurance agent.",
    example_vn: "Anh ấy liên hệ với đại lý bảo hiểm của mình.",
  },
  {
    english: "aggressive",
    vietnamese: "hung hăng, quyết liệt",
    type: "adj",
    example_en: "His aggressive behavior caused problems.",
    example_vn: "Hành vi hung hăng của anh ta gây ra rắc rối.",
  },
  {
    english: "ago",
    vietnamese: "trước đây",
    type: "adv",
    example_en: "I met her two years ago.",
    example_vn: "Tôi gặp cô ấy hai năm trước.",
  },
  {
    english: "agree",
    vietnamese: "đồng ý",
    type: "v",
    example_en: "I agree with your opinion.",
    example_vn: "Tôi đồng ý với ý kiến của bạn.",
  },
  {
    english: "agreement",
    vietnamese: "thỏa thuận",
    type: "n",
    example_en: "They signed an agreement.",
    example_vn: "Họ đã ký một thỏa thuận.",
  },
  {
    english: "ahead",
    vietnamese: "phía trước, trước",
    type: "adv",
    example_en: "Go ahead and start without me.",
    example_vn: "Cứ bắt đầu trước đi, không cần chờ tôi.",
  },
  {
    english: "aid",
    vietnamese: "viện trợ; giúp đỡ",
    type: "n., v.",
    example_en: "The organization provides aid to refugees.",
    example_vn: "Tổ chức này cung cấp viện trợ cho người tị nạn.",
  },
  {
    english: "aim",
    vietnamese: "mục tiêu; nhắm tới",
    type: "v., n.",
    example_en: "We aim to finish the project this month.",
    example_vn: "Chúng tôi đặt mục tiêu hoàn thành dự án trong tháng này.",
  },
  {
    english: "air",
    vietnamese: "không khí",
    type: "n",
    example_en: "The air is very clean here.",
    example_vn: "Không khí ở đây rất trong lành.",
  },
  {
    english: "aircraft",
    vietnamese: "máy bay",
    type: "n",
    example_en: "The aircraft landed safely.",
    example_vn: "Chiếc máy bay đã hạ cánh an toàn.",
  },
  {
    english: "airline",
    vietnamese: "hãng hàng không",
    type: "n",
    example_en: "This airline offers cheap flights.",
    example_vn: "Hãng hàng không này cung cấp các chuyến bay giá rẻ.",
  },
  {
    english: "airport",
    vietnamese: "sân bay",
    type: "n",
    example_en: "We arrived at the airport early.",
    example_vn: "Chúng tôi đến sân bay sớm.",
  },
  {
    english: "alarm",
    vietnamese: "báo động; báo thức",
    type: "n., v.",
    example_en: "The alarm went off at 6 a.m.",
    example_vn: "Chuông báo thức reo lúc 6 giờ sáng.",
  },
  {
    english: "album",
    vietnamese: "album",
    type: "n",
    example_en: "She released a new album.",
    example_vn: "Cô ấy phát hành một album mới.",
  },
  {
    english: "alcohol",
    vietnamese: "rượu, cồn",
    type: "n",
    example_en: "He avoids alcohol.",
    example_vn: "Anh ấy tránh uống rượu.",
  },
  {
    english: "alcoholic",
    vietnamese: "có cồn",
    type: "adj",
    example_en: "This drink is alcoholic.",
    example_vn: "Đồ uống này có cồn.",
  },
  {
    english: "alive",
    vietnamese: "còn sống",
    type: "adj",
    example_en: "The animal is still alive.",
    example_vn: "Con vật vẫn còn sống.",
  },
  {
    english: "all",
    vietnamese: "tất cả",
    type: "det., pron., adv.",
    example_en: "All students must attend.",
    example_vn: "Tất cả sinh viên phải tham dự.",
  },
  {
    english: "all right",
    vietnamese: "ổn, được",
    type: "adj., adv.",
    example_en: "Everything is all right now.",
    example_vn: "Mọi thứ giờ đã ổn.",
  },
  {
    english: "allow",
    vietnamese: "cho phép",
    type: "v",
    example_en: "They allow pets here.",
    example_vn: "Họ cho phép mang thú cưng vào đây.",
  },
  {
    english: "almost",
    vietnamese: "gần như",
    type: "adv",
    example_en: "I almost missed the bus.",
    example_vn: "Tôi suýt nữa thì lỡ chuyến xe buýt.",
  },
  {
    english: "alone",
    vietnamese: "một mình",
    type: "adj., adv.",
    example_en: "She lives alone.",
    example_vn: "Cô ấy sống một mình.",
  },
  {
    english: "along",
    vietnamese: "dọc theo, cùng với",
    type: "prep., adv.",
    example_en: "We walked along the river.",
    example_vn: "Chúng tôi đi dọc theo con sông.",
  },
  {
    english: "already",
    vietnamese: "đã rồi",
    type: "adv",
    example_en: "I have already eaten.",
    example_vn: "Tôi ăn rồi.",
  },
  {
    english: "also",
    vietnamese: "cũng",
    type: "adv",
    example_en: "She also wants to come.",
    example_vn: "Cô ấy cũng muốn đi.",
  },
  {
    english: "alter",
    vietnamese: "thay đổi",
    type: "v",
    example_en: "They altered the plan.",
    example_vn: "Họ đã thay đổi kế hoạch.",
  },
  {
    english: "alternative",
    vietnamese: "lựa chọn thay thế; thay thế",
    type: "n., adj.",
    example_en: "We need an alternative solution.",
    example_vn: "Chúng ta cần một giải pháp thay thế.",
  },
  {
    english: "although",
    vietnamese: "mặc dù",
    type: "conj.",
    example_en: "Although it was raining, we went out.",
    example_vn: "Mặc dù trời mưa, chúng tôi vẫn ra ngoài.",
  },
  {
    english: "always",
    vietnamese: "luôn luôn",
    type: "adv",
    example_en: "She always arrives on time.",
    example_vn: "Cô ấy luôn đến đúng giờ.",
  },
  {
    english: "amazed",
    vietnamese: "kinh ngạc",
    type: "adj",
    example_en: "I was amazed by the result.",
    example_vn: "Tôi rất kinh ngạc về kết quả.",
  },
  {
    english: "amazing",
    vietnamese: "đáng kinh ngạc",
    type: "adj",
    example_en: "The view is amazing.",
    example_vn: "Quang cảnh thật đáng kinh ngạc.",
  },
  {
    english: "ambition",
    vietnamese: "tham vọng, hoài bão",
    type: "n",
    example_en: "Her ambition is to become a doctor.",
    example_vn: "Hoài bão của cô ấy là trở thành bác sĩ.",
  },
  {
    english: "among",
    vietnamese: "trong số",
    type: "prep.",
    example_en: "She is popular among her colleagues.",
    example_vn: "Cô ấy được yêu mến trong số các đồng nghiệp.",
  },
  {
    english: "amount",
    vietnamese: "số lượng; lên tới",
    type: "n., v.",
    example_en: "A large amount of money was spent.",
    example_vn: "Một số tiền lớn đã được chi.",
  },
  {
    english: "analysis",
    vietnamese: "phân tích",
    type: "n",
    example_en: "The analysis shows positive results.",
    example_vn: "Bản phân tích cho thấy kết quả tích cực.",
  },
  {
    english: "analyze",
    vietnamese: "phân tích",
    type: "v",
    example_en: "We need to analyze the data carefully.",
    example_vn: "Chúng ta cần phân tích dữ liệu một cách cẩn thận.",
  },
  {
    english: "ancient",
    vietnamese: "cổ xưa",
    type: "adj",
    example_en: "They studied ancient history.",
    example_vn: "Họ nghiên cứu lịch sử cổ đại.",
  },
  {
    english: "and",
    vietnamese: "và",
    type: "conj.",
    example_en: "I bought bread and milk.",
    example_vn: "Tôi mua bánh mì và sữa.",
  },
  {
    english: "anger",
    vietnamese: "sự tức giận",
    type: "n",
    example_en: "He spoke in anger.",
    example_vn: "Anh ấy nói trong cơn tức giận.",
  },
  {
    english: "angle",
    vietnamese: "góc, góc độ",
    type: "n",
    example_en: "Look at the problem from a different angle.",
    example_vn: "Hãy nhìn vấn đề từ một góc độ khác.",
  },
  {
    english: "angry",
    vietnamese: "tức giận",
    type: "adj",
    example_en: "She is angry about the delay.",
    example_vn: "Cô ấy tức giận vì sự chậm trễ.",
  },
  {
    english: "animal",
    vietnamese: "động vật",
    type: "n",
    example_en: "This zoo has many animals.",
    example_vn: "Sở thú này có nhiều động vật.",
  },
  {
    english: "ankle",
    vietnamese: "mắt cá chân",
    type: "n",
    example_en: "He injured his ankle while running.",
    example_vn: "Anh ấy bị đau mắt cá chân khi chạy.",
  },
  {
    english: "anniversary",
    vietnamese: "ngày kỷ niệm",
    type: "n",
    example_en: "They celebrated their wedding anniversary.",
    example_vn: "Họ tổ chức kỷ niệm ngày cưới.",
  },
  {
    english: "announce",
    vietnamese: "thông báo",
    type: "v",
    example_en: "The company announced the new policy.",
    example_vn: "Công ty đã thông báo chính sách mới.",
  },
  {
    english: "announcement",
    vietnamese: "thông báo",
    type: "n",
    example_en: "There was an important announcement this morning.",
    example_vn: "Sáng nay có một thông báo quan trọng.",
  },
  {
    english: "annoy",
    vietnamese: "làm phiền, chọc tức",
    type: "v",
    example_en: "Loud noise can annoy people.",
    example_vn: "Tiếng ồn lớn có thể làm phiền mọi người.",
  },
  {
    english: "annoyed",
    vietnamese: "bực mình",
    type: "adj",
    example_en: "She looks annoyed by the comment.",
    example_vn: "Cô ấy trông bực mình vì lời nhận xét đó.",
  },
  {
    english: "annoying",
    vietnamese: "gây khó chịu",
    type: "adj",
    example_en: "This sound is really annoying.",
    example_vn: "Âm thanh này thật sự gây khó chịu.",
  },
  {
    english: "annual",
    vietnamese: "hàng năm",
    type: "adj",
    example_en: "The company holds an annual meeting.",
    example_vn: "Công ty tổ chức họp thường niên.",
  },
  {
    english: "another",
    vietnamese: "khác, một cái khác",
    type: "det., pron.",
    example_en: "Can I have another cup of coffee?",
    example_vn: "Tôi có thể uống thêm một tách cà phê nữa không?",
  },
  {
    english: "answer",
    vietnamese: "câu trả lời; trả lời",
    type: "n., v.",
    example_en: "She answered the question clearly.",
    example_vn: "Cô ấy trả lời câu hỏi một cách rõ ràng.",
  },
  {
    english: "anxious",
    vietnamese: "lo lắng",
    type: "adj",
    example_en: "He feels anxious about the exam.",
    example_vn: "Anh ấy lo lắng về kỳ thi.",
  },
  {
    english: "any",
    vietnamese: "bất kỳ",
    type: "det., pron., adv.",
    example_en: "Do you have any questions?",
    example_vn: "Bạn có câu hỏi nào không?",
  },
  {
    english: "anybody",
    vietnamese: "bất kỳ ai",
    type: "pron.",
    example_en: "Anybody can make mistakes.",
    example_vn: "Bất kỳ ai cũng có thể mắc lỗi.",
  },
  {
    english: "anymore",
    vietnamese: "nữa, nữa nên",
    type: "adv",
    example_en: "I don't love her anymore.",
    example_vn: "Tôi không yêu cô ấy nữa.",
  },
  {
    english: "anyone",
    vietnamese: "bất kỳ ai",
    type: "pron.",
    example_en: "Is anyone home?",
    example_vn: "Có ai ở nhà không?",
  },
  {
    english: "anything",
    vietnamese: "bất cứ điều gì",
    type: "pron.",
    example_en: "I would do anything for you.",
    example_vn: "Tôi sẵn sàng làm bất cứ điều gì cho bạn.",
  },
  {
    english: "anyway",
    vietnamese: "dù sao đi nữa",
    type: "adv",
    example_en: "I don't like it, but I'll do it anyway.",
    example_vn: "Tôi không thích, nhưng tôi vẫn sẽ làm dù sao đi nữa.",
  },
  {
    english: "anywhere",
    vietnamese: "ở bất kỳ nơi nào",
    type: "adv",
    example_en: "We can go anywhere you want.",
    example_vn: "Chúng ta có thể đi bất kỳ nơi nào bạn muốn.",
  },
  {
    english: "apart",
    vietnamese: "riêng rẽ, tách biệt",
    type: "adv",
    example_en: "They lived apart for a year.",
    example_vn: "Họ sống riêng rẽ trong một năm.",
  },
  {
    english: "apartment",
    vietnamese: "căn hộ",
    type: "n",
    example_en: "She lives in a small apartment.",
    example_vn: "Cô ấy sống trong một căn hộ nhỏ.",
  },
  {
    english: "apology",
    vietnamese: "lời xin lỗi",
    type: "n",
    example_en: "He gave a sincere apology.",
    example_vn: "Anh ấy đã xin lỗi chân thành.",
  },
  {
    english: "apologize",
    vietnamese: "xin lỗi",
    type: "v",
    example_en: "I sincerely apologize for my mistake.",
    example_vn: "Tôi xin lỗi chân thành vì sai lầm của tôi.",
  },
  {
    english: "appear",
    vietnamese: "xuất hiện, dường như",
    type: "v",
    example_en: "She appeared suddenly from behind the door.",
    example_vn: "Cô ấy xuất hiện bất ngờ từ phía sau cửa.",
  },
  {
    english: "appearance",
    vietnamese: "sự xuất hiện, vẻ ngoài",
    type: "n",
    example_en: "Her appearance was striking.",
    example_vn: "Vẻ ngoài của cô ấy rất ấn tượng.",
  },
  {
    english: "appetite",
    vietnamese: "cơn đói",
    type: "n",
    example_en: "She had a good appetite.",
    example_vn: "Cô ấy ăn rất ngon.",
  },
  {
    english: "apple",
    vietnamese: "quả táo",
    type: "n",
    example_en: "An apple a day keeps the doctor away.",
    example_vn: "Ăn một quả táo mỗi ngày tốt cho sức khỏe.",
  },
  {
    english: "application",
    vietnamese: "ứng dụng, đơn xin",
    type: "n",
    example_en: "She submitted her job application.",
    example_vn: "Cô ấy đã nộp đơn xin việc.",
  },
  {
    english: "apply",
    vietnamese: "áp dụng, xin vào",
    type: "v",
    example_en: "Apply this cream to the affected area.",
    example_vn: "Áp dụng kem này vào vùng bị ảnh hưởng.",
  },
  {
    english: "appoint",
    vietnamese: "bổ nhiệm, sắp xếp",
    type: "v",
    example_en: "They appointed a new manager.",
    example_vn: "Họ đã bổ nhiệm một quản lý mới.",
  },
  {
    english: "appointment",
    vietnamese: "cuộc hẹn, bổ nhiệm",
    type: "n",
    example_en: "I have a doctor's appointment tomorrow.",
    example_vn: "Tôi có một cuộc hẹn với bác sĩ ngày mai.",
  },
  {
    english: "appreciate",
    vietnamese: "đánh giá cao, cảm kích",
    type: "v",
    example_en: "I appreciate your help.",
    example_vn: "Tôi cảm kích sự giúp đỡ của bạn.",
  },
  {
    english: "approach",
    vietnamese: "tiếp cận, phương pháp",
    type: "v., n.",
    example_en: "We need to approach this problem carefully.",
    example_vn: "Chúng ta cần tiếp cận vấn đề này một cách cẩn thận.",
  },
  {
    english: "appropriate",
    vietnamese: "thích hợp, phù hợp",
    type: "adj",
    example_en: "Formal clothes are appropriate for the meeting.",
    example_vn: "Quần áo trang trọng là thích hợp cho cuộc họp.",
  },
  {
    english: "approval",
    vietnamese: "sự chấp thuận",
    type: "n",
    example_en: "We got approval from the director.",
    example_vn: "Chúng tôi nhận được sự chấp thuận từ giám đốc.",
  },
  {
    english: "approve",
    vietnamese: "chấp thuận",
    type: "v",
    example_en: "The board approved the new plan.",
    example_vn: "Ban quản trị đã chấp thuận kế hoạch mới.",
  },
  {
    english: "april",
    vietnamese: "tháng tư",
    type: "n",
    example_en: "April is the fourth month of the year.",
    example_vn: "Tháng tư là tháng thứ tư của năm.",
  },
  {
    english: "arch",
    vietnamese: "vòm, cung",
    type: "n",
    example_en: "The bridge has a beautiful arch.",
    example_vn: "Cây cầu có một vòm cung đẹp.",
  },
  {
    english: "architect",
    vietnamese: "kiến trúc sư",
    type: "n",
    example_en: "The architect designed a modern building.",
    example_vn: "Kiến trúc sư đã thiết kế một tòa nhà hiện đại.",
  },
  {
    english: "architecture",
    vietnamese: "kiến trúc",
    type: "n",
    example_en: "The architecture of the city is stunning.",
    example_vn: "Kiến trúc của thành phố rất ngoạn mục.",
  },
  {
    english: "arctic",
    vietnamese: "bắc cực",
    type: "adj",
    example_en: "The Arctic is very cold.",
    example_vn: "Bắc Cực rất lạnh.",
  },
  {
    english: "area",
    vietnamese: "khu vực, diện tích",
    type: "n",
    example_en: "This area has many restaurants.",
    example_vn: "Khu vực này có nhiều nhà hàng.",
  },
  {
    english: "argue",
    vietnamese: "tranh luận",
    type: "v",
    example_en: "They argued about the best strategy.",
    example_vn: "Họ tranh luận về chiến lược tốt nhất.",
  },
  {
    english: "argument",
    vietnamese: "cuộc tranh luận, lý lẽ",
    type: "n",
    example_en: "His argument was very logical.",
    example_vn: "Lý lẽ của anh ấy rất logic.",
  },
  {
    english: "arise",
    vietnamese: "phát sinh, nảy sinh",
    type: "v",
    example_en: "Problems arose during the project.",
    example_vn: "Những vấn đề đã phát sinh trong dự án.",
  },
  {
    english: "arm",
    vietnamese: "cánh tay; vũ khí",
    type: "n.",
    example_en: "She broke her arm in the accident.",
    example_vn: "Cô ấy gãy cánh tay trong tai nạn.",
  },
  {
    english: "army",
    vietnamese: "quân đội",
    type: "n",
    example_en: "He serves in the army.",
    example_vn: "Anh ấy phục vụ trong quân đội.",
  },
  {
    english: "around",
    vietnamese: "xung quanh, vòng",
    type: "prep., adv.",
    example_en: "We walked around the park.",
    example_vn: "Chúng tôi đi vòng xung quanh công viên.",
  },
  {
    english: "arrange",
    vietnamese: "sắp xếp, tổ chức",
    type: "v",
    example_en: "She arranged the flowers in a vase.",
    example_vn: "Cô ấy sắp xếp những bông hoa vào một cái bình.",
  },
  {
    english: "arrangement",
    vietnamese: "sự sắp xếp",
    type: "n",
    example_en: "The arrangement of furniture looked good.",
    example_vn: "Cách sắp xếp đồ nội thất trông rất tốt.",
  },
  {
    english: "arrest",
    vietnamese: "bắt giữ",
    type: "v",
    example_en: "The police arrested the suspect.",
    example_vn: "Cảnh sát đã bắt giữ nghi phạm.",
  },
  {
    english: "arrival",
    vietnamese: "sự đến, sự tới",
    type: "n",
    example_en: "We celebrated her arrival at the station.",
    example_vn: "Chúng tôi chào mừng sự tới của cô ấy tại ga.",
  },
  {
    english: "arrive",
    vietnamese: "đến, tới",
    type: "v",
    example_en: "The train arrived on time.",
    example_vn: "Chuyến tàu đã tới đúng giờ.",
  },
  {
    english: "arrow",
    vietnamese: "mũi tên",
    type: "n",
    example_en: "The arrow hit the target.",
    example_vn: "Mũi tên đã bắn trúng mục tiêu.",
  },
  {
    english: "art",
    vietnamese: "nghệ thuật",
    type: "n",
    example_en: "She studied art in university.",
    example_vn: "Cô ấy học nghệ thuật ở đại học.",
  },
  {
    english: "article",
    vietnamese: "bài báo, mạo từ",
    type: "n",
    example_en: "I read an interesting article in the newspaper.",
    example_vn: "Tôi đọc một bài báo thú vị trên báo.",
  },
  {
    english: "artificial",
    vietnamese: "nhân tạo",
    type: "adj",
    example_en: "The artificial flowers look real.",
    example_vn: "Những bông hoa nhân tạo trông rất thực.",
  },
  {
    english: "artist",
    vietnamese: "nghệ sĩ",
    type: "n",
    example_en: "He is a talented artist.",
    example_vn: "Anh ấy là một nghệ sĩ tài năng.",
  },
  {
    english: "artistic",
    vietnamese: "thuộc nghệ thuật",
    type: "adj",
    example_en: "The painting has artistic value.",
    example_vn: "Bức tranh có giá trị nghệ thuật.",
  },
  {
    english: "as",
    vietnamese: "như, vì",
    type: "conj., prep., adv.",
    example_en: "As you know, the project is important.",
    example_vn: "Như bạn biết, dự án này rất quan trọng.",
  },
  {
    english: "ash",
    vietnamese: "tro",
    type: "n",
    example_en: "The volcano ejected ash into the sky.",
    example_vn: "Núi lửa phun tro vào bầu trời.",
  },
  {
    english: "ashamed",
    vietnamese: "xấu hổ",
    type: "adj",
    example_en: "She felt ashamed of her behavior.",
    example_vn: "Cô ấy cảm thấy xấu hổ vì hành động của mình.",
  },
  {
    english: "ask",
    vietnamese: "hỏi, yêu cầu",
    type: "v",
    example_en: "May I ask a question?",
    example_vn: "Tôi có thể hỏi một câu hỏi không?",
  },
  {
    english: "asleep",
    vietnamese: "ngủ",
    type: "adj., adv.",
    example_en: "The baby is asleep.",
    example_vn: "Bé ngủ rồi.",
  },
  {
    english: "aspect",
    vietnamese: "khía cạnh",
    type: "n",
    example_en: "We need to consider every aspect of the problem.",
    example_vn: "Chúng ta cần xem xét mọi khía cạnh của vấn đề.",
  },
  {
    english: "assist",
    vietnamese: "giúp đỡ",
    type: "v",
    example_en: "I will assist you with the project.",
    example_vn: "Tôi sẽ giúp bạn với dự án.",
  },
  {
    english: "assistance",
    vietnamese: "sự giúp đỡ",
    type: "n",
    example_en: "Do you need any assistance?",
    example_vn: "Bạn có cần sự giúp đỡ nào không?",
  },
  {
    english: "assistant",
    vietnamese: "trợ lý, phụ tá",
    type: "n",
    example_en: "She works as an assistant.",
    example_vn: "Cô ấy làm việc như một trợ lý.",
  },
  {
    english: "associate",
    vietnamese: "kết hợp, liên kết",
    type: "v., n.",
    example_en: "I associate this song with my childhood.",
    example_vn: "Tôi liên kết bài hát này với tuổi thơ của tôi.",
  },
  {
    english: "association",
    vietnamese: "hiệp hội, tổ chức",
    type: "n",
    example_en: "She joined a professional association.",
    example_vn: "Cô ấy tham gia một hiệp hội chuyên nghiệp.",
  },
  {
    english: "assume",
    vietnamese: "giả định, cho rằng",
    type: "v",
    example_en: "I assume you are happy with the result.",
    example_vn: "Tôi giả định bạn hài lòng với kết quả.",
  },
  {
    english: "assumption",
    vietnamese: "giả định",
    type: "n",
    example_en: "His assumption was incorrect.",
    example_vn: "Giả định của anh ấy là sai.",
  },
  {
    english: "assure",
    vietnamese: "đảm bảo, cam đoan",
    type: "v",
    example_en: "I assure you everything will be fine.",
    example_vn: "Tôi đảm bảo mọi thứ sẽ ổn.",
  },
  {
    english: "at",
    vietnamese: "tại, ở",
    type: "prep.",
    example_en: "I am at home right now.",
    example_vn: "Tôi đang ở nhà lúc này.",
  },
  {
    english: "atom",
    vietnamese: "nguyên tử",
    type: "n",
    example_en: "An atom is the smallest unit of matter.",
    example_vn: "Nguyên tử là đơn vị nhỏ nhất của vật chất.",
  },
  {
    english: "attach",
    vietnamese: "gắn, buộc",
    type: "v",
    example_en: "Please attach the document to the email.",
    example_vn: "Vui lòng gắn tài liệu vào email.",
  },
  {
    english: "attack",
    vietnamese: "tấn công",
    type: "v., n.",
    example_en: "The enemy attacked at dawn.",
    example_vn: "Kẻ thù tấn công vào lúc bình minh.",
  },
  {
    english: "attain",
    vietnamese: "đạt được, hoàn thành",
    type: "v",
    example_en: "She attained her goal.",
    example_vn: "Cô ấy đã đạt được mục tiêu.",
  },
  {
    english: "attend",
    vietnamese: "tham dự, chăm sóc",
    type: "v",
    example_en: "Will you attend the meeting tomorrow?",
    example_vn: "Bạn có sẽ tham dự cuộc họp ngày mai không?",
  },
  {
    english: "attendance",
    vietnamese: "sự tham dự, điểm danh",
    type: "n",
    example_en: "Good attendance is important.",
    example_vn: "Sự tham dự tốt là quan trọng.",
  },
  {
    english: "attention",
    vietnamese: "sự chú ý",
    type: "n",
    example_en: "Please pay attention to the instructions.",
    example_vn: "Vui lòng chú ý đến các hướng dẫn.",
  },
  {
    english: "attire",
    vietnamese: "trang phục",
    type: "n",
    example_en: "Her attire was very stylish.",
    example_vn: "Trang phục của cô ấy rất thời trang.",
  },
  {
    english: "attitude",
    vietnamese: "thái độ, quan điểm",
    type: "n",
    example_en: "His attitude toward work is positive.",
    example_vn: "Thái độ của anh ấy đối với công việc là tích cực.",
  },
]
